### ISSUE TITLE
Backport for 1.20.1

### ISSUE THREAD

**Issue by PseudoSquared** [LegendarySpy/Biome-Replacer-Neoforge#4]
Need an updated version for Forge 1.20.1, should also mention I am trying to replace vanilla biomes with a BOP biome, which I saw is a known bug.

**Comment by LegendarySpy** [comment]
Ok, that was alot faster then expected, Im gonna upload a working basic version here in a min or 2, the modrinth version which will come out a bit later should have the newer features that have been added over time. BOP is probably not working yet

**Comment by LegendarySpy** [comment]
Ok this should work, if you could test it out at somepoint that would be great - the only update this has so far is it's using the updated config file, biome tags won't work right now: https://dropover.cloud/40adf0

**Comment by PseudoSquared** [comment]
Funnily enough I looked at my phone a few minutes after you made your comment on the other thread. I'm currently testing out the file you've given me. Pardon my stupidity but what do you mean when you say "biome tags won't work right now," would you mind using Discord for easier communication? My tag is pseudosquared

**Comment by LegendarySpy** [comment]
Yea - no problem, here if you wanna join the community server: https://discord.gg/C4nqeMcT

**Comment by JpnRndr01** [comment]
LegendarySpy could you post a new link please? thanks

**Comment by LegendarySpy** [comment]
https://modrinth.com/mod/biome-replacer-neoforge/version/1.2-1.20.1

I can't fully confirm it's bug free so please report any more bugs you find, I'm going to close this issue for now. Feel free to open a new one if anything else pops up.

**Comment by PseudoSquared** [comment]
Thank you so much! I'll test the mod later today and see if it works with terralith biomes and such. Would you be able to post another discord link by any chance so I can communicate with you easier again? Honestly, I left last time because I had assumed you'd moved on from this, but this is certainly a pleasant suprise!

**Comment by LegendarySpy** [comment]
I'm glad you're excited to test it out! If there are any bugs, it'll give me a chance to fix them before the general public encounters them. Here's the Discord link: https://discord.gg/z3h4d3Ux3p
